// Code generated by mockery v2.23.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ConnectionRetrierFn is an autogenerated mock type for the ConnectionRetrierFn type
type ConnectionRetrierFn struct {
	mock.Mock
}

type ConnectionRetrierFn_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectionRetrierFn) EXPECT() *ConnectionRetrierFn_Expecter {
	return &ConnectionRetrierFn_Expecter{mock: &_m.Mock}
}

// DoWithRetryFn provides a mock function with given fields:
func (_m *ConnectionRetrierFn) DoWithRetryFn() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConnectionRetrierFn_DoWithRetryFn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoWithRetryFn'
type ConnectionRetrierFn_DoWithRetryFn_Call struct {
	*mock.Call
}

// DoWithRetryFn is a helper method to define mock.On call
func (_e *ConnectionRetrierFn_Expecter) DoWithRetryFn() *ConnectionRetrierFn_DoWithRetryFn_Call {
	return &ConnectionRetrierFn_DoWithRetryFn_Call{Call: _e.mock.On("DoWithRetryFn")}
}

func (_c *ConnectionRetrierFn_DoWithRetryFn_Call) Run(run func()) *ConnectionRetrierFn_DoWithRetryFn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnectionRetrierFn_DoWithRetryFn_Call) Return(_a0 error) *ConnectionRetrierFn_DoWithRetryFn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConnectionRetrierFn_DoWithRetryFn_Call) RunAndReturn(run func() error) *ConnectionRetrierFn_DoWithRetryFn_Call {
	_c.Call.Return(run)
	return _c
}

// NewConnectionRetrierFn creates a new instance of ConnectionRetrierFn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConnectionRetrierFn(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConnectionRetrierFn {
	mock := &ConnectionRetrierFn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
