// Code generated by mockery v2.23.4. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/Chystik/runtime-metrics/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MetricsService is an autogenerated mock type for the MetricsService type
type MetricsService struct {
	mock.Mock
}

type MetricsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MetricsService) EXPECT() *MetricsService_Expecter {
	return &MetricsService_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *MetricsService) Get(_a0 context.Context, _a1 models.Metric) (models.Metric, error) {
	ret := _m.Called(_a0, _a1)

	var r0 models.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Metric) (models.Metric, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Metric) models.Metric); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(models.Metric)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Metric) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MetricsService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.Metric
func (_e *MetricsService_Expecter) Get(_a0 interface{}, _a1 interface{}) *MetricsService_Get_Call {
	return &MetricsService_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *MetricsService_Get_Call) Run(run func(_a0 context.Context, _a1 models.Metric)) *MetricsService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Metric))
	})
	return _c
}

func (_c *MetricsService_Get_Call) Return(_a0 models.Metric, _a1 error) *MetricsService_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_Get_Call) RunAndReturn(run func(context.Context, models.Metric) (models.Metric, error)) *MetricsService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: _a0
func (_m *MetricsService) GetAll(_a0 context.Context) ([]models.Metric, error) {
	ret := _m.Called(_a0)

	var r0 []models.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Metric, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Metric); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MetricsService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MetricsService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MetricsService_Expecter) GetAll(_a0 interface{}) *MetricsService_GetAll_Call {
	return &MetricsService_GetAll_Call{Call: _e.mock.On("GetAll", _a0)}
}

func (_c *MetricsService_GetAll_Call) Run(run func(_a0 context.Context)) *MetricsService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MetricsService_GetAll_Call) Return(_a0 []models.Metric, _a1 error) *MetricsService_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MetricsService_GetAll_Call) RunAndReturn(run func(context.Context) ([]models.Metric, error)) *MetricsService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCounter provides a mock function with given fields: _a0, _a1
func (_m *MetricsService) UpdateCounter(_a0 context.Context, _a1 models.Metric) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Metric) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MetricsService_UpdateCounter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCounter'
type MetricsService_UpdateCounter_Call struct {
	*mock.Call
}

// UpdateCounter is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.Metric
func (_e *MetricsService_Expecter) UpdateCounter(_a0 interface{}, _a1 interface{}) *MetricsService_UpdateCounter_Call {
	return &MetricsService_UpdateCounter_Call{Call: _e.mock.On("UpdateCounter", _a0, _a1)}
}

func (_c *MetricsService_UpdateCounter_Call) Run(run func(_a0 context.Context, _a1 models.Metric)) *MetricsService_UpdateCounter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Metric))
	})
	return _c
}

func (_c *MetricsService_UpdateCounter_Call) Return(_a0 error) *MetricsService_UpdateCounter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsService_UpdateCounter_Call) RunAndReturn(run func(context.Context, models.Metric) error) *MetricsService_UpdateCounter_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGauge provides a mock function with given fields: _a0, _a1
func (_m *MetricsService) UpdateGauge(_a0 context.Context, _a1 models.Metric) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Metric) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MetricsService_UpdateGauge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGauge'
type MetricsService_UpdateGauge_Call struct {
	*mock.Call
}

// UpdateGauge is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 models.Metric
func (_e *MetricsService_Expecter) UpdateGauge(_a0 interface{}, _a1 interface{}) *MetricsService_UpdateGauge_Call {
	return &MetricsService_UpdateGauge_Call{Call: _e.mock.On("UpdateGauge", _a0, _a1)}
}

func (_c *MetricsService_UpdateGauge_Call) Run(run func(_a0 context.Context, _a1 models.Metric)) *MetricsService_UpdateGauge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Metric))
	})
	return _c
}

func (_c *MetricsService_UpdateGauge_Call) Return(_a0 error) *MetricsService_UpdateGauge_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsService_UpdateGauge_Call) RunAndReturn(run func(context.Context, models.Metric) error) *MetricsService_UpdateGauge_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateList provides a mock function with given fields: _a0, _a1
func (_m *MetricsService) UpdateList(_a0 context.Context, _a1 []models.Metric) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Metric) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MetricsService_UpdateList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateList'
type MetricsService_UpdateList_Call struct {
	*mock.Call
}

// UpdateList is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []models.Metric
func (_e *MetricsService_Expecter) UpdateList(_a0 interface{}, _a1 interface{}) *MetricsService_UpdateList_Call {
	return &MetricsService_UpdateList_Call{Call: _e.mock.On("UpdateList", _a0, _a1)}
}

func (_c *MetricsService_UpdateList_Call) Run(run func(_a0 context.Context, _a1 []models.Metric)) *MetricsService_UpdateList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Metric))
	})
	return _c
}

func (_c *MetricsService_UpdateList_Call) Return(_a0 error) *MetricsService_UpdateList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MetricsService_UpdateList_Call) RunAndReturn(run func(context.Context, []models.Metric) error) *MetricsService_UpdateList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMetricsService creates a new instance of MetricsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsService {
	mock := &MetricsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
