// Code generated by mockery v2.23.4. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MetricsHandlers is an autogenerated mock type for the MetricsHandlers type
type MetricsHandlers struct {
	mock.Mock
}

// AllMetrics provides a mock function with given fields: w, r
func (_m *MetricsHandlers) AllMetrics(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetMetric provides a mock function with given fields: w, r
func (_m *MetricsHandlers) GetMetric(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetMetricJSON provides a mock function with given fields: w, r
func (_m *MetricsHandlers) GetMetricJSON(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdateMetric provides a mock function with given fields: w, r
func (_m *MetricsHandlers) UpdateMetric(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UpdateMetricJSON provides a mock function with given fields: w, r
func (_m *MetricsHandlers) UpdateMetricJSON(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewMetricsHandlers creates a new instance of MetricsHandlers. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMetricsHandlers(t interface {
	mock.TestingT
	Cleanup(func())
}) *MetricsHandlers {
	mock := &MetricsHandlers{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
